
- name: Initialize Replication COntext for Mtree Replication ID {{ ID }}
  uri:
    method: POST
    url: "{{ ppdd_baseurl }}:{{ ppdd_port }}/{{ ppdd_api_ver }}/dd-systems/{{ system_id }}/mtree-replications/{{ ID }}/initialize"
    body_format: json
    headers:
      X-DD-AUTH-TOKEN: "{{ access_token }}"    
    status_code: 200,201,400,500, -1
    validate_certs: false
  register: result  
  when: not ansible_check_mode
- set_fact:
    init: "{{ result.json if result.json is defined}}"
- debug:
    msg:  "{{ init if init is defined }}"
    verbosity: 0
#  when: file_systems_block_storages is defined  


